export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}
import { MswComponent } from "@/components/msw.component"
import "./global.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<MswComponent /> {children}
			</body>
		</html>
	)
}
