export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};
import { MswComponent } from "@/components/msw/msw.component";
import "./global.css";
import QueryProvider from "@/providers/queryProvider";
import RecoilProvider from "@/providers/recoilProvider";
import AuthProvider from "@/providers/authProvider";
import Layout from "@/components/Layout";
import ModalProvider from "@/providers/modalProvider";
import "react-toastify/dist/ReactToastify.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<QueryProvider>
					<RecoilProvider>
						<AuthProvider />
						<ModalProvider />
						<MswComponent />
						<Layout>{children}</Layout>
					</RecoilProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
